name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:

  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.get_version.outputs.VERSION}}
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

  docker:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            REVISION=${{needs.get_version.outputs.version}}
          push: true
          tags: loniowsky/eszop-frontend:latest,loniowsky/eszop-frontend:${{needs.get_version.outputs.version}}